In [12]:
from open3d import *
import pcl
import numpy as np
import os
import pptk # HERE visualization tool
import pcl.pcl_visualization # PCL visualization tool

In [13]:
# path to a particular point-cloud object
# fname = '/home/jonathan/Desktop/univ_wash_rgbd/apple_1_1_1.pcd' 
apple_1 = '/home/msr/Desktop/3d_point_cloud_gan/apple_1_1_1.pcd'

# confirm current directory
# os.getcwd()

'/home/msr/Desktop/3d_point_cloud_gan'

In [23]:
# testing different point cloud libraries

# pcl
# cloud = pcl.load(fname,format='pcd')
# print ('Loaded ' + str(cloud.width * cloud.height) + ' data points from ' + fname + ' with the following fields: ')
# for i in range(0, cloud.size):
#     print ('x: '  + str(cloud[i][0]) + ', y : ' + str(cloud[i][1])  + ', z : ' + str(cloud[i][2]))

# open3d - apple view 1
cloud_1 = read_point_cloud(apple_1)
print(cloud_1)

print("X Y Z values...")
print(np.asarray(cloud_1.points))

draw_geometries([cloud_1])

PointCloud with 3161 points.
X Y Z values...
[[-0.00776376  0.73799998  0.02846712]
 [-0.0064698   0.73799998  0.02846712]
 [-0.00517584  0.73799998  0.02846712]
 ...
 [-0.01398283  0.72500002 -0.0572025 ]
 [-0.01271167  0.72500002 -0.0572025 ]
 [-0.0114405   0.72500002 -0.0572025 ]]


In [25]:
# open3d - apple view 2
apple_2 = '/home/msr/Desktop/3d_point_cloud_gan/apple_1_1_2.pcd'
cloud_2 = read_point_cloud(apple_2)
print(cloud_2)

print("X Y Z values...")
print(np.asarray(cloud_2.points))

draw_geometries([cloud_2])


PointCloud with 3172 points.
X Y Z values...
[[-0.00647857  0.73900002  0.02850569]
 [-0.00518285  0.73900002  0.02850569]
 [-0.00388188  0.73799998  0.02846712]
 ...
 [-0.0126766   0.72299999 -0.0570447 ]
 [-0.01140894  0.72299999 -0.0570447 ]
 [-0.01014128  0.72299999 -0.0570447 ]]


In [26]:
# open3d - apple view 3
apple_3 = '/home/msr/Desktop/3d_point_cloud_gan/apple_1_1_3.pcd'
cloud_3 = read_point_cloud(apple_3)
print(cloud_3)

print("X Y Z values...")
print(np.asarray(cloud_3.points))

draw_geometries([cloud_3])

PointCloud with 3198 points.
X Y Z values...
[[-0.00516181  0.736       0.02838997]
 [-0.00387136  0.736       0.02838997]
 [-0.00258091  0.736       0.02838997]
 ...
 [-0.015254    0.72500002 -0.0572025 ]
 [-0.01394426  0.72299999 -0.0570447 ]
 [-0.0126766   0.72299999 -0.0570447 ]]
